# Data Science 7 Days of code
## Day 4
### Instruções
Uma das aplicações que mais interessam empresas de todos os setores são os sistemas de recomendação: aplicações que aprendem, a partir de dados históricos, como sugerir os melhores itens para clientes a fim de maximizar alguma métrica de negócio, como faturamento, taxa de conversão, dentre outras.<br>Minha proposta para este desafio é que você crie um sistema de recomendações a partir do MovieLens.<br>
Pense em como uma empresa como a Netflix utilizaria um sistema desse jeito. Você consegue criar um sistema que recomenda 5 filmes para o usuário com base em comportamentos passados?

## Importação do arquivo
De acordo com o arquivo *README* da pasta *ml-100k* mostra que o *data set* que contém as informações principais é *u.data*, que mostra as recomentações dos usuários para os filmes então vou escolher um usuário para recomendar filmes com base nas suas avaliações.

### Visualizando dados
**Agora irei ler os dados e nomear as colunas pois o *data set* veio sem colunas, mas é possível nomeá-las, pois o *README* diz o nome das colunas de cada *data set*.**

In [318]:
import pandas as pd

colunas = ["user id", "item id", "rating", "timestamp"]
dados = pd.read_table("../Day4/ml-100k/u.data", names=colunas)
dados

       user id  item id  rating  timestamp
0          196      242       3  881250949
1          186      302       3  891717742
2           22      377       1  878887116
3          244       51       2  880606923
4          166      346       1  886397596
...        ...      ...     ...        ...
99995      880      476       3  880175444
99996      716      204       5  879795543
99997      276     1090       1  874795795
99998       13      225       2  882399156
99999       12      203       3  879959583

[100000 rows x 4 columns]

## Agrupando usuários
**Para fazer um sistema de recomendação irie analisar a avaliação de um usuário qualquer e analisar os tipos de filmes que esse usuário gosta, logo em seguida recomendar filmes que ele não tenha avaliado ainda baseado nos gêneros que ele goste.**

In [319]:
selecao_usuario_196 = dados["user id"] == 196
df_user196 = dados[selecao_usuario_196]
df_user196

       user id  item id  rating  timestamp
0          196      242       3  881250949
940        196      393       4  881251863
1133       196      381       4  881251728
1812       196      251       3  881251274
1896       196      655       5  881251793
2374       196       67       5  881252017
6910       196      306       4  881251021
7517       196      238       4  881251820
7842       196      663       5  881251911
10017      196      111       4  881251793
10254      196      580       2  881252056
10981      196       25       4  881251955
13733      196      286       5  881250949
14606      196       94       3  881252172
16834      196      692       5  881252017
17102      196        8       5  881251753
17830      196      428       4  881251702
18853      196     1118       4  881252128
21605      196       70       3  881251842
22271      196       66       3  881251911
22773      196      257       2  881251577
23189      196      108       4  881252110
24030      196      202       3  881251728
25726      196      340       3  881251045
32721      196      287       3  881251884
33536      196      116       3  881251753
35197      196      382       4  881251843
36281      196      285       5  881251753
41539      196     1241       3  881251642
42384      196     1007       4  881251601
50147      196      411       4  881252090
52726      196      153       5  881251820
56628      196       13       2  881251955
59165      196      762       3  881251955
59607      196      173       2  881251820
60199      196     1022       4  881251143
60706      196      845       4  881251954
78787      196      269       3  881250949
87863      196      110       1  881252305

## Filtrando dados

**Agora vou filtrar para selecionar os filmes com avaliação acima de 3.**

In [320]:
selecao_maior3 = df_user196["rating"] >= 3
df_user196_maior3 = df_user196[selecao_maior3]
df_user196_maior3

       user id  item id  rating  timestamp
0          196      242       3  881250949
940        196      393       4  881251863
1133       196      381       4  881251728
1812       196      251       3  881251274
1896       196      655       5  881251793
2374       196       67       5  881252017
6910       196      306       4  881251021
7517       196      238       4  881251820
7842       196      663       5  881251911
10017      196      111       4  881251793
10981      196       25       4  881251955
13733      196      286       5  881250949
14606      196       94       3  881252172
16834      196      692       5  881252017
17102      196        8       5  881251753
17830      196      428       4  881251702
18853      196     1118       4  881252128
21605      196       70       3  881251842
22271      196       66       3  881251911
23189      196      108       4  881252110
24030      196      202       3  881251728
25726      196      340       3  881251045
32721      196      287       3  881251884
33536      196      116       3  881251753
35197      196      382       4  881251843
36281      196      285       5  881251753
41539      196     1241       3  881251642
42384      196     1007       4  881251601
50147      196      411       4  881252090
52726      196      153       5  881251820
59165      196      762       3  881251955
60199      196     1022       4  881251143
60706      196      845       4  881251954
78787      196      269       3  881250949

**Como não temos os nomes dos filmes teremos que ler outro *data set* com as especificações de cada filme.**

In [321]:
colunas_filmes =  ["movie id", "movie title", "release date", "video release date",
              "IMDb URL", "unknown", "Action", "Adventure", "Animation",
              "Children's", "Comedy", "Crime", "Documentary", "Drama", "Fantasy",
              "Film-Noir", "Horror", "Musical", "Mystery", "Romance", "Sci-Fi",
              "Thriller", "War", "Western"]
filmes = pd.read_table("ml-100k/u.item", encoding="latin-1", sep="|", names=colunas_filmes)
filmes

,movie id,movie title,release date,video release date,IMDb URL,unknown,Action,Adventure,Animation,Children's,...,Fantasy,Film-Noir,Horror,Musical,Mystery,Romance,Sci-Fi,Thriller,War,Western
0,1,Toy Story (1995),01-Jan-1995,NaN,http://us.imdb.com/M/title-exact?Toy%20Story%2...,0,0,0,1,1,...,0,0,0,0,0,0,0,0,0,0
1,2,GoldenEye (1995),01-Jan-1995,NaN,http://us.imdb.com/M/title-exact?GoldenEye%20(...,0,1,1,0,0,...,0,0,0,0,0,0,0,1,0,0
2,3,Four Rooms (1995),01-Jan-1995,NaN,http://us.imdb.com/M/title-exact?Four%20Rooms%...,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
3,4,Get Shorty (1995),01-Jan-1995,NaN,http://us.imdb.com/M/title-exact?Get%20Shorty%...,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,5,Copycat (1995),01-Jan-1995,NaN,http://us.imdb.com/M/title-exact?Copycat%20(1995),0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1677,1678,Mat' i syn (1997),06-Feb-1998,NaN,http://us.imdb.com/M/title-exact?Mat%27+i+syn+...,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1678,1679,B. Monkey (1998),06-Feb-1998,NaN,http://us.imdb.com/M/title-exact?B%2E+Monkey+(...,0,0,0,0,0,...,0,0,0,0,0,1,0,1,0,0
1679,1680,Sliding Doors (1998),01-Jan-1998,NaN,http://us.imdb.com/Title?Sliding+Doors+(1998),0,0,0,0,0,...,0,0,0,0,0,1,0,0,0,0
1680,1681,You So Crazy (1994),01-Jan-1994,NaN,http://us.imdb.com/M/title-exact?You%20So%20Cr...,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1681,1682,Scream of Stone (Schrei aus Stein) (1991),08-Mar-1996,NaN,http://us.imdb.com/M/title-exact?Schrei%20aus%...,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

**Na célula abaixo criarei uma seleção para filtrar, apenas para mostrar os filmes que o nosso usuário avaliou maior que 3.**

In [322]:
selecao_filmes_user196 = filmes["movie id"].isin(df_user196_maior3["item id"])
filmes_do_user196 = filmes[selecao_filmes_user196]
filmes_do_user196

,movie id,movie title,release date,video release date,IMDb URL,unknown,Action,Adventure,Animation,Children's,...,Fantasy,Film-Noir,Horror,Musical,Mystery,Romance,Sci-Fi,Thriller,War,Western
7,8,Babe (1995),01-Jan-1995,NaN,http://us.imdb.com/M/title-exact?Babe%20(1995),0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
24,25,"Birdcage, The (1996)",08-Mar-1996,NaN,"http://us.imdb.com/M/title-exact?Birdcage,%20T...",0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
65,66,While You Were Sleeping (1995),01-Jan-1995,NaN,http://us.imdb.com/M/title-exact?While%20You%2...,0,0,0,0,0,...,0,0,0,0,0,1,0,0,0,0
66,67,Ace Ventura: Pet Detective (1994),01-Jan-1994,NaN,http://us.imdb.com/M/title-exact?Ace%20Ventura...,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
69,70,Four Weddings and a Funeral (1994),01-Jan-1994,NaN,http://us.imdb.com/M/title-exact?Four%20Weddin...,0,0,0,0,0,...,0,0,0,0,0,1,0,0,0,0
93,94,Home Alone (1990),01-Jan-1990,NaN,http://us.imdb.com/M/title-exact?Home%20Alone%...,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
107,108,Kids in the Hall: Brain Candy (1996),12-Apr-1996,NaN,http://us.imdb.com/M/title-exact?Kids%20in%20t...,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
110,111,"Truth About Cats & Dogs, The (1996)",26-Apr-1996,NaN,http://us.imdb.com/M/title-exact?Truth%20About...,0,0,0,0,0,...,0,0,0,0,0,1,0,0,0,0
115,116,Cold Comfort Farm (1995),23-Apr-1996,NaN,http://us.imdb.com/M/title-exact?Cold%20Comfor...,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
152,153,"Fish Called Wanda, A (1988)",01-Jan-1988,NaN,http://us.imdb.com/M/title-exact?Fish%20Called...,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
201,202,Groundhog Day (1993),01-Jan-1993,NaN,http://us.imdb.com/M/title-exact?Groundhog%20D...,0,0,0,0,0,...,0,0,0,0,0,1,0,0,0,0
237,238,Raising Arizona (1987),01-Jan-1987,NaN,http://us.imdb.com/M/title-exact?Raising%20Ari...,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
241,242,Kolya (1996),24-Jan-1997,NaN,http://us.imdb.com/M/title-exact?Kolya%20(1996),0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
250,251,Shall We Dance? (1996),11-Jul-1997,NaN,http://us.imdb.com/M/title-exact?Shall%20we%20...,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
268,269,"Full Monty, The (1997)",01-Jan-1997,NaN,http://us.imdb.com/M/title-exact?Full+Monty%2C...,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
284,285,Secrets & Lies (1996),04-Oct-1996,NaN,http://us.imdb.com/M/title-exact?Secrets%20&%2...,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
285,286,"English Patient, The (1996)",15-Nov-1996,NaN,http://us.imdb.com/M/title-exact?English%20Pat...,0,0,0,0,0,...,0,0,0,0,0,1,0,0,1,0
286,287,Marvin's Room (1996),18-Dec-1996,NaN,http://us.imdb.com/M/title-exact?Marvin's%20Ro...,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
305,306,"Mrs. Brown (Her Majesty, Mrs. Brown) (1997)",01-Jan-1997,NaN,http://us.imdb.com/M/title-exact?Her+Majesty%2...,0,0,0,0,0,...,0,0,0,0,0,1,0,0,0,0
339,340,Boogie Nights (1997),01-Jan-1997,NaN,http://us.imdb.com/M/title-exact?Boogie+Nights...,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
380,381,Muriel's Wedding (1994),01-Jan-1994,NaN,http://us.imdb.com/M/title-exact?Muriel's%20We...,0,0,0,0,0,...,0,0,0,0,0,1,0,0,0,0
381,382,"Adventures of Priscilla, Queen of the Desert, ...",01-Jan-1994,NaN,http://us.imdb.com/M/title-exact?Adventures%20...,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
392,393,Mrs. Doubtfire (1993),01-Jan-1993,NaN,http://us.imdb.com/M/title-exact?Mrs.%20Doubtf...,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
410,411,"Nutty Professor, The (1996)",28-Jun-1996,NaN,http://us.imdb.com/M/title-exact?Nutty%20Profe...,0,0,0,0,0,...,1,0,0,0,0,1,1,0,0,0
427,428,Harold and Maude (1971),01-Jan-1971,NaN,http://us.imdb.com/M/title-exact?Harold%20and%...,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
654,655,Stand by Me (1986),01-Jan-1986,NaN,http://us.imdb.com/M/title-exact?Stand%20by%20...,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
662,663,Being There (1979),01-Jan-1979,NaN,http://us.imdb.com/M/title-exact?Being%20There...,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
691,692,"American President, The (1995)",01-Jan-1995,NaN,http://us.imdb.com/M/title-exact?American%20Pr...,0,0,0,0,0,...,0,0,0,0,0,1,0,0,0,0
761,762,Beautiful Girls (1996),09-Feb-1996,NaN,http://us.imdb.com/M/title-exact?Beautiful%20G...,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
844,845,That Thing You Do! (1996),28-Sep-1996,NaN,http://us.imdb.com/M/title-exact?That%20Thing%...,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1006,1007,Waiting for Guffman (1996),31-Jan-1997,NaN,http://us.imdb.com/M/title-exact?Waiting%20for...,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1021,1022,"Fast, Cheap & Out of Control (1997)",01-Jan-1997,NaN,"http://us.imdb.com/M/title-exact?Fast,+Cheap+&...",0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1117,1118,Up in Smoke (1978),01-Jan-1978,NaN,http://us.imdb.com/M/title-exact?Up%20in%20Smo...,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1240,1241,"Van, The (1996)",27-Jun-1997,NaN,http://us.imdb.com/M/title-exact?Van%2C%20The%...,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

**Com essa filtragem podemos ver os nomes dos filmes que o *user196* avaliou maior que 3**

## Analisando filmes do user 196

**A célula abaixo contém a soma dos gêneros dos filmes que o *user 196* avaliou maior que 3.**

In [323]:
filmes_do_user196.loc[:,"unknown":].sum()

unknown         0
Action          0
Adventure       1
Animation       0
Children's      2
Comedy         27
Crime           0
Documentary     1
Drama          11
Fantasy         1
Film-Noir       0
Horror          0
Musical         0
Mystery         0
Romance         9
Sci-Fi          1
Thriller        0
War             1
Western         0
dtype: int64

**Como podemos ver o *user 196* gosta majoritariamente de filmes de comédia e drama, logo irei recomendar filmes de comédia e/ou de drama.**

## Recomendando filmes

**Aqui vou fazer um seleção de filmes que o *user_196* não viu e depois filtrá-la para filmes de comédia e romance.**

In [324]:
selecao_filmes_naovistos = filmes["movie id"].isin(df_user196["item id"].unique())
df_filmes_naovistos = filmes[~selecao_filmes_naovistos]
df_filmes_naovistos

,movie id,movie title,release date,video release date,IMDb URL,unknown,Action,Adventure,Animation,Children's,...,Fantasy,Film-Noir,Horror,Musical,Mystery,Romance,Sci-Fi,Thriller,War,Western
0,1,Toy Story (1995),01-Jan-1995,NaN,http://us.imdb.com/M/title-exact?Toy%20Story%2...,0,0,0,1,1,...,0,0,0,0,0,0,0,0,0,0
1,2,GoldenEye (1995),01-Jan-1995,NaN,http://us.imdb.com/M/title-exact?GoldenEye%20(...,0,1,1,0,0,...,0,0,0,0,0,0,0,1,0,0
2,3,Four Rooms (1995),01-Jan-1995,NaN,http://us.imdb.com/M/title-exact?Four%20Rooms%...,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
3,4,Get Shorty (1995),01-Jan-1995,NaN,http://us.imdb.com/M/title-exact?Get%20Shorty%...,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,5,Copycat (1995),01-Jan-1995,NaN,http://us.imdb.com/M/title-exact?Copycat%20(1995),0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1677,1678,Mat' i syn (1997),06-Feb-1998,NaN,http://us.imdb.com/M/title-exact?Mat%27+i+syn+...,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1678,1679,B. Monkey (1998),06-Feb-1998,NaN,http://us.imdb.com/M/title-exact?B%2E+Monkey+(...,0,0,0,0,0,...,0,0,0,0,0,1,0,1,0,0
1679,1680,Sliding Doors (1998),01-Jan-1998,NaN,http://us.imdb.com/Title?Sliding+Doors+(1998),0,0,0,0,0,...,0,0,0,0,0,1,0,0,0,0
1680,1681,You So Crazy (1994),01-Jan-1994,NaN,http://us.imdb.com/M/title-exact?You%20So%20Cr...,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1681,1682,Scream of Stone (Schrei aus Stein) (1991),08-Mar-1996,NaN,http://us.imdb.com/M/title-exact?Schrei%20aus%...,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

**Agora vou filtrar para mostrar apenas filmes de comédia ou romance.**

In [325]:
selecao_romanceoucomedia = (df_filmes_naovistos["Romance"] == 1) | (df_filmes_naovistos["Comedy"] == 1)
df_filmes_naovistos[selecao_romanceoucomedia]

,movie id,movie title,release date,video release date,IMDb URL,unknown,Action,Adventure,Animation,Children's,...,Fantasy,Film-Noir,Horror,Musical,Mystery,Romance,Sci-Fi,Thriller,War,Western
0,1,Toy Story (1995),01-Jan-1995,NaN,http://us.imdb.com/M/title-exact?Toy%20Story%2...,0,0,0,1,1,...,0,0,0,0,0,0,0,0,0,0
3,4,Get Shorty (1995),01-Jan-1995,NaN,http://us.imdb.com/M/title-exact?Get%20Shorty%...,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
13,14,"Postino, Il (1994)",01-Jan-1994,NaN,"http://us.imdb.com/M/title-exact?Postino,%20Il...",0,0,0,0,0,...,0,0,0,0,0,1,0,0,0,0
15,16,French Twist (Gazon maudit) (1995),01-Jan-1995,NaN,http://us.imdb.com/M/title-exact?Gazon%20maudi...,0,0,0,0,0,...,0,0,0,0,0,1,0,0,0,0
16,17,From Dusk Till Dawn (1996),05-Feb-1996,NaN,http://us.imdb.com/M/title-exact?From%20Dusk%2...,0,1,0,0,0,...,0,0,1,0,0,0,0,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1667,1668,Wedding Bell Blues (1996),13-Jun-1997,NaN,http://us.imdb.com/M/title-exact?Wedding%20Bel...,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1669,1670,Tainted (1998),01-Feb-1998,NaN,http://us.imdb.com/M/title-exact?Tainted+(1998),0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
1678,1679,B. Monkey (1998),06-Feb-1998,NaN,http://us.imdb.com/M/title-exact?B%2E+Monkey+(...,0,0,0,0,0,...,0,0,0,0,0,1,0,1,0,0
1679,1680,Sliding Doors (1998),01-Jan-1998,NaN,http://us.imdb.com/Title?Sliding+Doors+(1998),0,0,0,0,0,...,0,0,0,0,0,1,0,0,0,0
1680,1681,You So Crazy (1994),01-Jan-1994,NaN,http://us.imdb.com/M/title-exact?You%20So%20Cr...,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

**Agora vou filtrar para mostrar apenas filmes de comédia e romance.**

In [326]:
selecao_romanceecomedia = (df_filmes_naovistos["Romance"] == 1) & (df_filmes_naovistos["Comedy"] == 1)
df_filmes_naovistos[selecao_romanceecomedia]

,movie id,movie title,release date,video release date,IMDb URL,unknown,Action,Adventure,Animation,Children's,...,Fantasy,Film-Noir,Horror,Musical,Mystery,Romance,Sci-Fi,Thriller,War,Western
15,16,French Twist (Gazon maudit) (1995),01-Jan-1995,NaN,http://us.imdb.com/M/title-exact?Gazon%20maudi...,0,0,0,0,0,...,0,0,0,0,0,1,0,0,0,0
48,49,I.Q. (1994),01-Jan-1994,NaN,http://us.imdb.com/M/title-exact?I.Q.%20(1994),0,0,0,0,0,...,0,0,0,0,0,1,0,0,0,0
68,69,Forrest Gump (1994),01-Jan-1994,NaN,http://us.imdb.com/M/title-exact?Forrest%20Gum...,0,0,0,0,0,...,0,0,0,0,0,1,0,0,1,0
80,81,"Hudsucker Proxy, The (1994)",01-Jan-1994,NaN,http://us.imdb.com/M/title-exact?Hudsucker%20P...,0,0,0,0,0,...,0,0,0,0,0,1,0,0,0,0
82,83,Much Ado About Nothing (1993),01-Jan-1993,NaN,http://us.imdb.com/M/title-exact?Much%20Ado%20...,0,0,0,0,0,...,0,0,0,0,0,1,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1520,1521,Mr. Wonderful (1993),01-Jan-1993,NaN,http://us.imdb.com/M/title-exact?Mr.%20Wonderf...,0,0,0,0,0,...,0,0,0,0,0,1,0,0,0,0
1524,1525,"Object of My Affection, The (1998)",20-Mar-1998,NaN,http://us.imdb.com/Title?Object+of+My+Affectio...,0,0,0,0,0,...,0,0,0,0,0,1,0,0,0,0
1567,1568,Vermont Is For Lovers (1992),01-Jan-1992,NaN,http://us.imdb.com/M/title-exact?Vermont%20Is%...,0,0,0,0,0,...,0,0,0,0,0,1,0,0,0,0
1654,1655,"Favor, The (1994)",01-Jan-1994,NaN,"http://us.imdb.com/M/title-exact?Favor,%20The%...",0,0,0,0,0,...,0,0,0,0,0,1,0,0,0,0
1655,1656,Little City (1998),20-Feb-1998,NaN,http://us.imdb.com/M/title-exact?Little+City+(...,0,0,0,0,0,...,0,0,0,0,0,1,0,0,0,0

## Dia 4 finalizado
Com esses códigos consegui filtrar e selecionar filmes específicos para um usuário baseados em suas avaliações. Com esses dois data frames finais podemos recomendar qualquer filme de romance ou comédia ou romance e comédia.